# Implementing Naive Bayes:

In [75]:
#  Importing required Liabraries:
import pandas as pd 
import numpy as np 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [76]:
# Loading Dataset:
train_data=pd.read_csv('train.csv')
test_data=pd.read_csv('test.csv')

In [77]:
print(train_data.head())
print('---------------------------------------------------------------------------')
print(test_data.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
--

In [78]:
# Dropping Columns not needed for analyisis:
train_data=train_data.drop(["Name","Cabin","Ticket"], axis=1)

In [79]:
test_data=test_data.drop(["Name","Ticket"],axis=1)

In [80]:
print(train_data.head())
print('---------------------------------------------------------------------------')
print(test_data.head())

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S
---------------------------------------------------------------------------
   PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0          892       3    male  34.5      0      0   7.8292        Q
1          893       3  female  47.0      1      0   7.0000        S
2          894       2    male  62.0      0      0   9.6875        Q
3          895       3    male  27.0      0      0   8.6625        S
4          896       3  female  22.0      1      1  12.2875        S


In [81]:
# Preprcessing:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [82]:
train_data['Sex']=le.fit_transform(train_data['Sex'])
train_data['Embarked']=le.fit_transform(train_data['Embarked'])
test_data['Sex']=le.fit_transform(test_data['Sex'])
test_data['Embarked']=le.fit_transform(test_data['Embarked'])

In [83]:
print(train_data.head())
print('---------------------------------------------------------------------------')
print(test_data.head())

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2
---------------------------------------------------------------------------
   PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          892       3    1  34.5      0      0   7.8292         1
1          893       3    0  47.0      1      0   7.0000         2
2          894       2    1  62.0      0      0   9.6875         1
3          895       3    1  27.0      0      0   8.6625         2
4          896       3    0  22.0      1      1  12.2875         2


In [84]:
train_data.shape

(889, 9)

In [85]:
test_data.shape

(417, 8)

In [86]:
train_data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [87]:
test_data.isna().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [88]:
# Spliting the datasets for analysis:
train_x=train_data.drop('Survived',axis=1)
train_y=train_data['Survived']

In [89]:
train_x.head(2)

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1       3    1  22.0      1      0   7.2500         2
1            2       1    0  38.0      1      0  71.2833         0

In [90]:
train_y.head(2)

0    0
1    1
Name: Survived, dtype: int64

In [91]:
model=GaussianNB()
model.fit(train_x,train_y)

GaussianNB()

In [92]:
# Prediction on Training dataset:
predict_train = model.predict(train_x)
print(predict_train)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 1 0 1 0 0
 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 1 0 1
 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0
 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0
 1 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 1 0 1 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1
 0 0 1 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0
 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 0 0 1 0
 1 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1
 0 0 1 0 1 1 1 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 1 0 0 0
 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 1 0
 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0
 0 1 1 0 1 1 0 0 0 0 0 1 

In [93]:
print('Training Accuracy:', accuracy_score(train_y,predict_train)*100,'%')

Training Accuracy: 79.19010123734533 %


In [94]:
# Predition on Test Dataset:
predict_test = model.predict(test_data)
print(predict_test)

[0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1
 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0
 0 0 1 0 1 0 0 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 1
 0 1 1 0 1 0 0 0 1 0 0 1 0 1 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1
 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1
 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0
 1 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1
 1 1 1 1 1 0 1 0 0 0]


# Principal Component Analysis:

In [95]:
# Importing Libraries:
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn import svm, datasets
 
irisdata=sns.load_dataset('iris')
irisdata.head()

C:\Users\Akshay\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [96]:
irisdata.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
148           6.2          3.4           5.4          2.3   virginica
104           6.5          3.0           5.8          2.2   virginica
81            5.5          2.4           3.7          1.0  versicolor
11            4.8          3.4           1.6          0.2      setosa
99            5.7          2.8           4.1          1.3  versicolor

In [97]:
irisdata.shape

(150, 5)

In [98]:
# Spliting and Analysis on the dataset:
X=irisdata.drop('species',axis=1)
y=irisdata['species']

from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print('------------------------------------------------------------------------------')
print(X_test)

[[-0.33535015 -0.08972404  0.36977135  0.35026641]
 [-0.33535015 -0.55784944  0.59938357  1.01323122]
 [-1.05826067  1.31465217 -1.40972338 -1.37344209]
 [-0.09437998 -0.79191214  0.71418969  0.88063825]
 [-1.29923084  0.84652677 -1.29491727 -1.37344209]
 [ 0.14659019 -1.96222564  0.08275607 -0.3126984 ]
 [-0.57632033 -0.08972404  0.36977135  0.35026641]
 [-0.45583524  2.71902838 -1.40972338 -1.37344209]
 [ 0.50804544 -1.26003754  0.59938357  0.35026641]
 [ 0.8695007  -0.32378674  0.42717441  0.08508048]
 [ 1.59241121  1.31465217  1.28822024  1.67619602]
 [ 1.59241121 -0.08972404  1.11601108  0.48285937]
 [ 0.74901562 -0.08972404  0.94380191  0.74804529]
 [-0.93777558  1.78277757 -1.1227081  -1.10825617]
 [ 0.74901562 -0.08972404  1.11601108  1.27841714]
 [ 0.8695007  -0.08972404  0.3123683   0.21767345]
 [ 0.38756036  0.84652677  0.88639885  1.4110101 ]
 [ 0.26707527 -0.08972404  0.42717441  0.21767345]
 [ 0.98998579 -0.08972404  0.65678663  0.61545233]
 [-0.09437998 -0.79191214  0.14

In [99]:
# PCA
from sklearn.decomposition import PCA
pca=PCA()
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)

In [100]:
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.72787458, 0.23075051, 0.03540468, 0.00597023])

**Since only first two principle components cotributed to the majority of the analysis part thus, we will reduce our to computation on just those two components.**

In [101]:
# PCA
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.72787458, 0.23075051])

**Performing RadomForestClassifier Algorithm of the iris dataset basis the principle componets we identified above.**

In [103]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [104]:
from sklearn.metrics import confusion_matrix,accuracy_score
print('Confuision Matrix:\n',confusion_matrix(y_test,y_pred),'\n')
print('Accuracy Score:',accuracy_score(y_test,y_pred)*100,'%')

Confuision Matrix:
 [[13  0  0]
 [ 0  6  1]
 [ 0  6  4]] 

Accuracy Score: 76.66666666666667 %


In [105]:
# PCA
from sklearn.decomposition import PCA
pca=PCA(n_components=1)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.75929014])

In [106]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print('Confuision Matrix:\n',confusion_matrix(y_test,y_pred),'\n')
print('Accuracy Score:',accuracy_score(y_test,y_pred)*100,'%')

Confuision Matrix:
 [[13  0  0]
 [ 0  7  0]
 [ 0  6  4]] 

Accuracy Score: 80.0 %


In [113]:
# PCA
from sklearn.decomposition import PCA
pca=PCA()
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_ratio_
explained_variance

array([1.])

In [114]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print('Confuision Matrix:\n',confusion_matrix(y_test,y_pred),'\n')
print('Accuracy Score:',accuracy_score(y_test,y_pred)*100,'%')

Confuision Matrix:
 [[13  0  0]
 [ 0  7  0]
 [ 0  6  4]] 

Accuracy Score: 80.0 %
