# Combining Arrays using Stack


# Please Scroll-Down for the solution of Assignment Day14-15(Heading is mentioned).
**Below are some practice codes done during the live session**

In [8]:
from numpy import array
from numpy import vstack,hstack
a1 = array([1,2,3])
a2 = array([4,5,6])
print(a1)
print(a2)

[1 2 3]
[4 5 6]


In [10]:
a3 = vstack((a1,a2))
print(a3)

[[1 2 3]
 [4 5 6]]


In [11]:
a4 = hstack((a1,a2))
print(a4)

[1 2 3 4 5 6]


In [13]:
a5 = array([[1,2,3],[4,5,6]])
a6= array([[11,22,33],[44,55,66]])
a5.shape
a6.shape

(2, 3)

In [14]:
vstack((a5,a6))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [15]:
hstack((a5,a6))

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [16]:
a7 = array([77,88,99])
a7.shape

(3,)

In [21]:
vstack((a7,a6))

array([[77, 88, 99],
       [11, 22, 33],
       [44, 55, 66]])

In [23]:
hstack((a7,a1))

array([77, 88, 99,  1,  2,  3])

# Array Reshapping - Data Shape

In [24]:
data = array([11,22,33,44,55])
data.shape

(5,)

In [26]:
data1 = array([[11,22],
              [33,44],
              [55,66]])
data1.shape

(3, 2)

In [27]:
data1.shape[0]

3

In [30]:
print(data)
data.shape
data.shape[0]

[11 22 33 44 55]


5

In [33]:
data2=data.reshape(data.shape[0],1)
print(data2)

[[11]
 [22]
 [33]
 [44]
 [55]]


In [34]:
data2.shape

(5, 1)

In [38]:
data3=data2.reshape(data2.shape[0],data2.shape[1],1)
print(data3)
data3.shape

[[[11]]

 [[22]]

 [[33]]

 [[44]]

 [[55]]]


(5, 1, 1)

# Python Pandas - Series 

In [47]:
import pandas as pd
ser=pd.Series()
print(ser)

Series([], dtype: float64)


C:\Users\Akshay\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


In [47]:
l=[1,2,3,4]
m=array(l)
s=pd.Series(l)
print(s)
print(m)
print(l)

0    1
1    2
2    3
3    4
dtype: int64
[1 2 3 4]
[1, 2, 3, 4]


In [50]:
d= array(['a','b','c','d'])
s = pd.Series(d,index=[9,10,11,12])
s

9     a
10    b
11    c
12    d
dtype: object

In [51]:
s[10]

'b'

In [52]:
dict = {'a': 0,'b':1,'c':2}
s = pd.Series(dict)
print(s)

a    0
b    1
c    2
dtype: int64


In [53]:
s[::-1]

c    2
b    1
a    0
dtype: int64

# Day14-15 Assignment Solution.

# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
arr1=np.empty((3,3,3))
print("The Array is-")
print(arr1)
print("The Shape of Array is-")
print(arr1.shape)

The Array is-
[[[5.12449761e-312 5.12449680e-312 1.69120145e-306]
  [6.23061763e-307 8.45593934e-307 7.56593017e-307]
  [1.11261027e-306 1.11261502e-306 1.42410839e-306]]

 [[7.56597770e-307 6.23059726e-307 1.42419530e-306]
  [9.79101761e-307 1.42417629e-306 9.34603679e-307]
  [1.78019761e-306 1.78020848e-306 7.56599807e-307]]

 [[1.42418172e-306 2.04712906e-306 7.56589622e-307]
  [1.11258277e-307 8.90111708e-307 2.11389826e-307]
  [1.11260619e-306 5.55962897e-312 1.17076152e+214]]]
The Shape of Array is-
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
arr2=np.zeros((5,5))
print("Initial Matrix-")
print(arr2)
for i in range(len(arr2)):
    for j in range(len(arr2)):
        if(i==j+1):
            arr2[i][j]=i
print("Final Matrix-")
print(arr2)

Initial Matrix-
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Final Matrix-
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [11]:
arr3=np.zeros((8,8)) 
print("Initial Matrix-")
print(arr3)
for i in range(len(arr3)):
    for j in range(len(arr3)):
        if(j%2!=0):
            arr3[i][j]=1
print("Final Matrix-")
print(arr3)

Initial Matrix-
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Final Matrix-
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 4. Normalize a 5x5 random matrix

In [12]:
arr4=np.random.randn(5,5)
print("The random matrix is-")
print(arr4)
normal=np.linalg.norm(arr4)
print("The norm value of random matrix is-")
print(normal)
arr5=np.divide(arr4,normal)
print("The normalized random mattrix is-")
print(arr5)

The random matrix is-
[[-0.95924984  0.27395916 -0.19264877  0.70216468  0.66763159]
 [-0.65677831 -0.52391071 -1.07789069  0.02568501  0.71324871]
 [-0.3804196   1.17042152  0.69584509  0.31076425 -0.87676365]
 [-0.6942869  -0.25062017  0.31673506 -1.31613367  0.44268919]
 [-0.70126452  1.19704136  0.49331313  1.80318203  1.70960058]]
The norm value of random matrix is-
4.257680851563247
The normalized random mattrix is-
[[-0.22529867  0.06434469 -0.04524735  0.16491717  0.1568064 ]
 [-0.15425729 -0.12305072 -0.25316381  0.00603263  0.16752047]
 [-0.08934902  0.27489649  0.16343289  0.07298909 -0.20592517]
 [-0.16306692 -0.05886307  0.07439145 -0.30911985  0.10397425]
 [-0.16470575  0.28114868  0.11586428  0.42351273  0.40153328]]


# 5. How to find common values between two arrays?

In [13]:
arr6=np.array([1,2,3,4,5])
print("The 1st array is-")
print(arr6)
arr7=np.array([2,4,6,8,10])
print("The 2nd array is-")
print(arr7)
cvalues=np.intersect1d(arr6,arr7)
print("Common values between two arrays are-")
print(cvalues)

The 1st array is-
[1 2 3 4 5]
The 2nd array is-
[ 2  4  6  8 10]
Common values between two arrays are-
[2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [14]:
yesterday =np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ",yesterday)
today= np.datetime64('today', 'D')
print("Today's Date: ",today)
tomorrow= np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-27
Today's Date:  2020-07-28
Tomorrow's Date:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [19]:
arr8=np.array([1,2,3])
arr9=np.array([1,2,3])
comparison = arr8 == arr9
equalArrays = comparison.all()
print('The two arrays are equal - True Or False?')
print("Output:",equalArrays)

The two arrays are equal - True Or False?
Output: True


# 8.Create random vector of size 10 and replace the maximum value by 0

In [21]:
a=np.random.randn(10,1)
print("The random vector is-")
print(a)
val=np.amax(a)
print("The maximum value in the vector is-")
print(val)
b=np.where(a==val)
a[b]=0
print("The new vector is-")
print(a)

The random vector is-
[[ 0.08388021]
 [ 0.99814365]
 [-0.31593467]
 [ 1.08279703]
 [ 0.61537388]
 [-0.80157793]
 [-1.02768146]
 [ 0.37693913]
 [-0.44283792]
 [-1.45715426]]
The maximum value in the vector is-
1.0827970328193461
The new vector is-
[[ 0.08388021]
 [ 0.99814365]
 [-0.31593467]
 [ 0.        ]
 [ 0.61537388]
 [-0.80157793]
 [-1.02768146]
 [ 0.37693913]
 [-0.44283792]
 [-1.45715426]]


# 9. How to print all the values of an array?

In [26]:
arr10=np.random.randn(3,3)#creates a random array of given order
print("The array is:")
print(arr10)
for i in range(len(arr10)):
    for j in range(len(arr10)):
        print("The element at index(",i,", ",j,") is:",arr10[i][j])

The array is:
[[ 1.45615194 -1.62819844 -0.30150773]
 [-2.47396126 -0.5031483   0.87941203]
 [-1.09303705  0.49856645 -0.15361216]]
The element at index( 0 ,  0 ) is: 1.4561519389118787
The element at index( 0 ,  1 ) is: -1.628198439291689
The element at index( 0 ,  2 ) is: -0.3015077260811214
The element at index( 1 ,  0 ) is: -2.4739612566094644
The element at index( 1 ,  1 ) is: -0.5031483039485465
The element at index( 1 ,  2 ) is: 0.8794120290322006
The element at index( 2 ,  0 ) is: -1.093037051890148
The element at index( 2 ,  1 ) is: 0.49856644772236214
The element at index( 2 ,  2 ) is: -0.1536121561150879


# 10.Subtract the mean of each row of a matrix

In [27]:
arr11=np.random.randn(3,3)
print("The matrix is-")
print(arr11)
print("The mean value of each row is-")
arr12=np.mean(arr11,axis=1)
print(arr12)
arr13=arr11-arr12
print("The matrix after the mean is subtracted-")
print(arr13)

The matrix is-
[[-0.315706    0.55329253  0.22016606]
 [-1.70129193 -2.33436441  0.45765784]
 [ 0.86100752  0.79450244 -1.40942295]]
The mean value of each row is-
[ 0.1525842  -1.19266616  0.082029  ]
The matrix after the mean is subtracted-
[[-0.4682902   1.7459587   0.13813706]
 [-1.85387612 -1.14169825  0.37562884]
 [ 0.70842332  1.98716861 -1.49145195]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [29]:
arr14 = np.random.randn(10,1)
print("The original vector is:")
print(arr14)
arr15=np.random.randint(0,len(arr14),4)
print("The Index values are:")
print(arr15)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(arr14,arr15,1)
print(arr14)

The original vector is:
[[-1.10851776]
 [-0.25209531]
 [ 0.99889355]
 [ 1.24590341]
 [ 0.57318175]
 [ 0.80419575]
 [-0.86260003]
 [-1.48926766]
 [ 0.01242279]
 [-0.65586388]]
The Index values are:
[0 0 1 8]
Final vector after adding 1 to corresponding elements at the specified indices:
[[ 0.89148224]
 [ 0.74790469]
 [ 0.99889355]
 [ 1.24590341]
 [ 0.57318175]
 [ 0.80419575]
 [-0.86260003]
 [-1.48926766]
 [ 1.01242279]
 [-0.65586388]]


# 12.How to get the diagonal of a dot product?

In [32]:
arr16=np.random.randn(3,3)
print("The first 3X3 array is- ")
print(arr16)
arr17=np.random.randn(3,3)
print("The second 3X3 array is- ")
print(arr17)
arr18=np.dot(arr16,arr17)
print("The corresponding dot product is- ")
print(arr18)
arr19=np.diag(arr18)
print("The corresponding diagonal elements are- ")
print(arr19)

The first 3X3 array is- 
[[ 0.84185735  1.11673552 -0.29964405]
 [ 2.89158413 -0.10826212  0.01097432]
 [ 1.49042049  0.62693911  1.01378953]]
The second 3X3 array is- 
[[-0.98864597  1.10122337  0.44152259]
 [ 1.2235175  -0.23467448 -0.65881254]
 [-1.26593414  0.19438261 -0.12259178]]
The corresponding dot product is- 
[[ 0.91337621  0.60675807 -0.32728643]
 [-3.00510635  3.2118196   1.34667879]
 [-1.98981801  1.69122232  0.12073671]]
The corresponding diagonal elements are- 
[0.91337621 3.2118196  0.12073671]


# 13.How to find the most frequent value in an array?

In [35]:
arr20=np.array([1,2,4,5,4,3,2,7,8,9,10,5,5,5,5,5,5,5,6,3,3,5,3,6,6,7,6,6,8])
np.argmax(np.bincount(arr20))

5

# 14.How to get the n largest values of an array

In [41]:
arr21=np.arange(10)
np.random.shuffle(arr21)
c=int(input("Enter the value of n:"))
print("The",c,"th largest value of the array are:")
print (arr21[np.argpartition(-arr21,c)[:c]])

Enter the value of n:5
The 5 th largest value of the array are:
[7 8 9 6 5]


# 15.How to create a record array from a regular array?

In [46]:
arr22 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:")
print(arr22)
arr23 = np.core.records.fromarrays(arr22.T,names='a,b,c',formats = 'S80, f8, i8')
print("Record array:")
print(arr23)
print(type(arr23))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Record array:
[(b'1', 2., 3) (b'4', 5., 6) (b'7', 8., 9)]
<class 'numpy.recarray'>
